### ISSUE TITLE
Enable CORS in toolbox

### ISSUE THREAD

**Issue by lbwexler** [exhi/toolbox#105]
Would be nice to be able to do config diffs between local host and the dev servers.

**Comment by amcclain** [comment]
CORS is enabled - you can diff between toolbox and toolbox-dev.  Maybe some issue with localhost?

Note that you do need to log on to both instances give no SSO. I added some code a little while ago to catch an access denied and show a prompt asking if you are logged on to both with a suitable account.

**Comment by lbwexler** [comment]
Hmm -- am logged in, so do think it may be related to localhost

**Comment by amcclain** [comment]
Might need to add /api after remote URL - we've tried to get that right a few times and to my frustration I still don't think it is. 

But diffing will work.  Look at the URLs its attempting to call and ensure they are correct / actually there.

**Comment by lbwexler** [comment]
Yes -- confirming ATM correct -- CORS is enabled and I am happily diffing prod v. dev.  

Not sure what I was seeing in local host, but happily closing this for the time being.
