### ISSUE TITLE
Issues with Portfolio Example

### ISSUE THREAD

**Issue by lbwexler** [exhi/toolbox#110]
I discussed the following issues with Arjun:

+ Chart in Bottom right corner no longer rendering (regression)
+ Need to add buffering to selection reaction in main grid.  Response when keyboarding through here is very sluggish.
+ Looks like we need to be producing stable ids in our portfolio service, and passing them in to the local store here.  Selection state being lost when grid refreshed.

**Comment by amcclain** [comment]
1 - fixed - bad use of toFixed vs. round
3 - fixed - we had ids but were always selecting first - added check to only sel first if no sel

**Comment by lbwexler** [comment]
Thanks Anselm -- I took care of #2 just now, so we can close this out
