### ISSUE TITLE
Formats tab - more consistent / standard styling

### ISSUE THREAD

**Issue by amcclain** [exhi/toolbox#111]
These tabs are really cool, but would like this tab to look more like the rest of the app and use more standard components.

+ Fix missing borders
+ Remove inner titles
+ Use formField
+ Unwind / reduce custom styling against BP classes as a best practice
+ Standard fonts

**Comment by lbwexler** [comment]
Yikes- I think something may have regressed that makes this look worse than it did at merge time.

+ I don't necessarily agree that we need to use formField here -- although it certainly is an option.  

+ Yes to reducing styling against BP classes, but think this panel similar to the main HoistInput controls example itself, which makes heavy use of  BP targeted styling.
