### ISSUE TITLE
Custom Admin tab example

### ISSUE THREAD

**Issue by amcclain** [exhi/toolbox#132]
We should support the ability to add one or more app-specific tabs to the build-in admin console. Toolbox should provide an example of how to do so.

The tab itself could be a simple placeholder that makes it clear it's just to show the pattern - does not need to provide any specific functionality, unless there's something straightforward that really makes sense.

**Comment by shravnk** [comment]
See https://github.com/exhi/toolbox/tree/customAdminTab and https://github.com/exhi/hoist-react/tree/customAdminTab.

One question is whether we should support nested custom tabs in the admin app. I am thinking each item in `tabsToAppend` would take an option `children` argument, and the admin appModel would handle the rest.

**Comment by lbwexler** [comment]
Closing this in favor of 

https://github.com/exhi/toolbox/issues/215
