### ISSUE TITLE
NewsService not thread safe

### ISSUE THREAD

**Issue by shravnk** [exhi/toolbox#144]
Discovered this issue after upping Toolbox's monitor frequency. The service should be caching results as we have done elsewhere.

**Comment by shravnk** [comment]
See #161

**Comment by lbwexler** [comment]
This is actually an easy fix -- need to stop writing that list after it is installed!

Think this can be done more simply by just sorting the list before installing it, or setting the mutable false flag where we need to get a sorted copy of it. (these sorts are mutable, and guaranteed to trip this non-threadsafe object up)

**Comment by lbwexler** [comment]
Just fixed this here and here:  

https://github.com/exhi/toolbox/commit/76695e4d1a644d4b890d5ea873bfeff3ea311966
https://github.com/exhi/toolbox/commit/432d1dcef81e1a7be2a1358ecd9278120856189a

@YanaNirvana sent to you for review
