### ISSUE TITLE
Add Other › Popups examples tab

### ISSUE THREAD

**Issue by amcclain** [exhi/toolbox#174]
We have this in the mobile Toolbox, but would be useful to have on the desktop as well. A new tab under Other with buttons to launch our various popup alerts.  

Should have examples of `XH.alert()`, `XH.confirm()`, and `XH.toast()`, and include an example that makes it clear (if you look at the code) how to use the promise returned by XH.confirm.

**Comment by lbwexler** [comment]
Great!  Think this is a great next project for you Yana.  It's been a huge gap for us.  

Let's use the recent 'DockContainer' example as a good example of how to lay it out.  Basically, the summary text with a number of buttons.  Think even two rows of buttons will be fine.  The more examples and variations, the better.

**Comment by lbwexler** [comment]
👍
