### ISSUE TITLE
Minor Re-shuffling of Toolbox

### ISSUE THREAD

**Issue by lbwexler** [exhi/toolbox#180]
Would like to propose the following minor re-shuffling ion toolbox.

1) Rename "Forms" Tab to "Controls" 
 -  Rename subtab "Controls" to "Inputs"
 -  Rename subtab "Validation" to "Forms"
Add text above both subtabs to explain.   Think this is critical.  Its way too easy to think you need a FORM for every input.

2)  Nest "Icons" within "Other".    (Things just gettting too crowded at the top level!)

**Comment by amcclain** [comment]
Agree 100% on Controls -> Inputs.  Not so sure about "Controls" for the top-level tab - I think it's likely too generic. Understand the concern re. Forms seeming to indicate an actual `Form` is always required to use an input, but we could clarify in the explanatory text (which I also agree needs to be expanded / improved). 

Could go with longer "Inputs & Forms" but then I know that top bar is crowded. 😄 

Also agree 100% on Icons moving under Other.  Clear choice there.

**Comment by amcclain** [comment]
Happened to be in Toolbox on my laptop and that crowded top tabset caught my eye - moved Icons under other in 8fd87f823b
