### ISSUE TITLE
Toolbox synthetic data should be created on server

### ISSUE THREAD

**Issue by lbwexler** [exhi/toolbox#187]
+ Will better model actual real world patterns of data loading.
+ Will allow for more rapid execution of client testing, especially for our large data (grid and cube) examples
+ Will let us work through json parsing and serialization issues 
+ Especially need to do this for PortfolioService.

Only downside is that we pay for this data -- could be an issue if we are actually running through lots of tests on AWS. Still we mostly develop locally, and its worth it in any case!

**Comment by amcclain** [comment]
Can we also look to delete https://github.com/exhi/toolbox/tree/develop/client-app/src/core/data/charts as part of this change?  These are pretty big static JSON blobs bundled and shipped with Toolbox just for these chart examples.

**Comment by lbwexler** [comment]
sounds like a good idea.
