### ISSUE TITLE
'Grids' tab: 'Refresh' doesn't work for 'Tree' and 'Tree w/CheckBox'  sub-tabs

### ISSUE THREAD

**Issue by mpeckerman** [exhi/toolbox#199]
1. Open Hoist React Toolbox apps
2. Navigate to 'Grids' tab > 'Tree' sub-tab
3. Click 'Refresh' button
4. The 'Tree' panel is not being refreshed 

** Similar behavior 'Tree w/CheckBox' panel

**Comment by YanaNirvana** [comment]
Just to clarify, what visual indicator do we expect "refresh" to trigger?

**Comment by lbwexler** [comment]
a mask, I think.

If its already masking, but the refresh is instantaneous, perhaps we need
to insert a delay?

Thanks

**Comment by lbwexler** [comment]
Hi -- Refresh is indeed happening, just too fast for a mask to be renderered.

No need to insert a delay here, pending change to move this data to the server will take care of this issue.  Closing.
