### ISSUE TITLE
Clicking 'Esc' key doesn't close calendar popup 

### ISSUE THREAD

**Issue by mpeckerman** [exhi/toolbox#207]
1. Navigate to Toolbox > Forms > Controls page
2. Click 'Calendar' button inside DateInput field
3. 'Calendar' popup is rendered
4. Click 'ESC' key to close the popup 
5. Calendar popup is displayed

** Similar behavior when trying to close 'Calendar' via 'Esc' at Forms > Validations, Forms >  Toolbar Forms and Formats > Date

**Comment by TomTirapani** [comment]
Fixed in hoist-react PR: https://github.com/exhi/hoist-react/pull/1186
