### ISSUE TITLE
Admin-only Tab for developers

### ISSUE THREAD

**Issue by haynesjm42** [exhi/toolbox#215]
We need a tab which is only visible to users with the HOIST_ADMIN role which can serve as a place for us to put components used for developing/testing different parts of the framework which may not make sense to be visible to non-hoist-developers

**Comment by amcclain** [comment]
Cool.  One option for this would be to put it in the Admin app itself - that would give us a good example of a custom snap-in tab for App Admin, plus provide a place to stash stuff as described...

**Comment by lbwexler** [comment]
I would argue we should put WIP/Testing stuff in the Admin, as Anselm suggests.  

Simultaneously, we could also make the file uploader a proper example "app".  Might help to round 
out our "examples" and also naturally show that different apps can have different protection levels (e.g. example splash tile indicates "login required" -- and then if you click it you get the lockout page!)

**Comment by lbwexler** [comment]
Fixed here:  
https://github.com/exhi/toolbox/commit/2d3e72f0129

Moved a Cube Test and an GridPerformance there to get us started.
