### ISSUE TITLE
Toolbox -> Charts Tab -> Zoom Out option is not available

### ISSUE THREAD

**Issue by mpeckerman** [exhi/toolbox#29]
Navigate to Toolbox -> Charts Tab -> Click and Hold on a line segment and move the arrow to the left (right) to ZOOM IN -> The detailed info for the period specified will be displayed -> An option to ZOOM OUT is not available

**Comment by amcclain** [comment]
Closing this as we have opened exhi/hoist-react#545 to add this to the core toolkit.  Thanks for reporting!
