### ISSUE TITLE
Example wrapper panel support for "links to source"

### ISSUE THREAD

**Issue by amcclain** [exhi/toolbox#45]
Would be useful to pass link(s) to source in Github as props to wrapper panel and have them displayed in a standardized way.  Could be used to link directly to the example source itself (see how it's built) as well as any relevant hoist-react classes.

**Comment by lbwexler** [comment]
+ 1 here on this one.  Would be great to choose which branch of hoist react or toolbox you go to, depending on the the environment...

**Comment by lbwexler** [comment]
Hi Colin -- Can you take a look at this one?  Think its a very important feature, but hopefully not too much work

**Comment by YanaNirvana** [comment]
Discussion with Anselm:

* We want to accept multiple links, the best data structure is perhaps an array of objects, where
* root GitHub URL configurable, use XH.getConf('SourceUrls').toolbox
* support a `note` config in the obj, non-hyperlinked text after the link for additional clarification

**Comment by amcclain** [comment]
Thanks for posting those additional details Yana. 

I think we will find it useful to be able to include links to hoist-react source (the most common, for the components/models we are highlighting), Toolbox source (for an easy link to the source for exactly the module you are viewing), and maybe external links (for things like a link to the ag-grid docs).

Given that, we discussed parsing the URLs passed into the new prop to look for a leading token such as`$TB` or `$HR` - these would be pre-processed to sub in the root from the config, or leave the link alone to support external links.

In terms of display - if any links are configured, the wrapper should write a dedicated links panel into the layout.  I was thinking something that could be docked to e.g. the lower right corner and ideally collapsible.

**Comment by YanaNirvana** [comment]
I don't think we'll get much use out of supporting `$AG/path` since we might have to google for the exact docs (the `path` part of `$AG/path`), and at the same time, I'm happy to build that.

Thanks for giving more details on the display and reminder on the `$TB` and `$HR` :)

**Comment by YanaNirvana** [comment]
collapsible... 🤔How would you feel about using our shiny new docked panel in the bottom right? @amcclain  :D
