### ISSUE TITLE
Port over PIQ news feed as full-stack demo

### ISSUE THREAD

**Issue by amcclain** [exhi/toolbox#49]
(In general we plan to collapse the PIQ application into Toolbox, supplementing the current top-level Toolbox "component library" tabs with a few tabs that show more full-featured demos. I suggest this ticket as an initial project.)

The Sencha-toolkit version of PIQ has a `NewsService` that fetches real-world news articles from newsapi.org - see:

https://github.com/exhi/piq/blob/d88c450b6f023a23f7e5204d93e5b958c2764955/grails-app/services/io/xh/piq/app/NewsService.groovy#L11

Would like to bring this same server-side support to Toolbox (with any updates that seem prudent or desirable). It could then be paired with a client-side "News Demo" tab that presents all available articles in a grid, potentially with a master/detail view, a set of relevant filters by source, and a simple search feature.

The overall goal is to present a realistic full-stack example of fetching data from a remote API, providing caching and data-processing on the Grails server, and then presenting the data in a nice-looking client-side example of well-integrated components and best practices.

## Add-ons
- [ ] This service should also allow us to define a few status monitors, which would make for an additional demo of that core Hoist functionality (item count, most recent item age, etc).
- [ ] We could look for an opportunity to add a dedicated admin tab related to the news feature... This could demonstrate the pattern of installing custom admin snap-ins within an app.

**Comment by lbwexler** [comment]
Closing this, as the core of the work is done!  See that the new ticket relating to Status Monitors refers to it.
