### ISSUE TITLE
Create dedicated (secret) admin user credentials from (optional) instance config

### ISSUE THREAD

**Issue by amcclain** [exhi/toolbox#51]
We want the deployed Toolbox to be accessible to all visitors. We force a login prompt to demo/test a login process and the client-side component, but we embed the username/password right in that login box message so visitors know what to type.

That's great for the main app, but for the admin client I think it would be better _not_ to use this same public user. We do expose various configs related to sending emails, etc. and in general it seems like a step too far.

I suggest looking for `adminUsername` / `adminPassword` instanceConfig keys within Bootstrap. If they exist, we should create a dedicated user with that info and assign it the admin role. Otherwise, we can still make the default toolbox@xh.io user an admin.

We can then add a set of credentials to the deployed server instanceConfigs that won't be in code.

**Comment by lbwexler** [comment]
👍 Merged.  Took a slightly different approach to just warn if credentials not present
