### ISSUE TITLE
Clean up / consolidate Forms panel example

### ISSUE THREAD

**Issue by amcclain** [exhi/toolbox#56]
* Determine if there is value in having a dedicated example for validation vs. baking some reasonable validation rules into the primary form field display.
* Review sample inputs and determine if we want to "tell a story" with form inputs that map onto some real kind of form vs. deliberately keeping things generic (or a mix of both - e.g. have the generic inputs all laid out, and then some more specific form example with related "real-world" uses.

**Comment by lbwexler** [comment]
I do think there is value in the dedicated validation example.

**Comment by amcclain** [comment]
Closing this ticket - do not believe there are any actionable items off of this. We have the general inputs library example + the dedicated validation (+ "tell a story") form example.
