### ISSUE TITLE
Add Teamcity linter preflight checks to this project

### ISSUE THREAD

**Issue by amcclain** [exhi/toolbox#66]
Not urgent, but would be great to have TC run the standard workflow we have in place for validating pull requests and branches by running them through the linter and then reporting back to GitHub.

**Comment by lbwexler** [comment]
John -- what would it take to do this?  This has bitten me a bunch of times.

**Comment by lbwexler** [comment]
(also just trying to close any easily closeable bugs to take them off the table)

**Comment by haynesjm42** [comment]
Will take care of this today

**Comment by haynesjm42** [comment]
This is all setup now, should work the same as the hoist-react setup

**Comment by amcclain** [comment]
Thank you much! 🙏
