### ISSUE TITLE
Code generators

### ISSUE THREAD

**Issue by shravnk** [exhi/toolbox#91]
- Allow users to enter a set of parameters for an Hoist modal, component, etc.
- Continuously update the code generated by those parameters in a jsonInput.
- Click to execute the code, e.g. display the modal or render the component.
- Click to copy the code to the clipboard.
- Attached files demonstrate how this might be achieved for XH.toast(), XH.message(), et al

[Code Generator Files.zip](https://github.com/exhi/toolbox/files/2458719/Code.Generator.Files.zip

**Comment by lbwexler** [comment]
Closing this issue -- we may revisit in the future and certainly won't forget about the idea!
